import type { E2RObject } from "../models";
import { translate, type Locale, type MessageKey } from "../i18n";
import { buildEntityEndpointLabels } from "../entity-endpoint-display";
type CreationMode = "entity" | "relation";
type Props = { locale: Locale; mode: CreationMode; entities: E2RObject[]; name: string; description: string; source: string; target: string; onNameChange: (value: string) => void; onDescriptionChange: (value: string) => void; onSourceChange: (value: string) => void; onTargetChange: (value: string) => void; onSave: () => void; onCancel: () => void };
export function CreationDialog({ locale, mode, entities, name, description, source, target, onNameChange, onDescriptionChange, onSourceChange, onTargetChange, onSave, onCancel }: Props) {
  const t = (key: MessageKey) => translate(locale, key);
  const endpointLabels = buildEntityEndpointLabels(entities);
  return <aside className="detail creation-dialog" role="dialog" aria-modal="true" aria-label={mode === "entity" ? t("createEntity") : t("createRelation")}><div className="detail-header"><h3>{mode === "entity" ? t("createEntity") : t("createRelation")}</h3></div>{mode === "relation" && <><label htmlFor="creation-source">{t("sourceEntity")}</label><select id="creation-source" value={source} onChange={(event) => onSourceChange(event.target.value)}><option value="">{t("selectSource")}</option>{entities.map((entity) => <option key={entity.id} value={entity.id}>{endpointLabels.get(entity.id) ?? entity.id}</option>)}</select><label htmlFor="creation-target">{t("targetEntity")}</label><select id="creation-target" value={target} onChange={(event) => onTargetChange(event.target.value)}><option value="">{t("selectTarget")}</option>{entities.map((entity) => <option key={entity.id} value={entity.id}>{endpointLabels.get(entity.id) ?? entity.id}</option>)}</select></>}<label htmlFor="creation-name">{t("name")}</label><input id="creation-name" autoComplete="off" value={name} onChange={(event) => onNameChange(event.target.value)} /><label htmlFor="creation-description">{t("description")}</label><textarea id="creation-description" rows={4} value={description} onChange={(event) => onDescriptionChange(event.target.value)} /><div className="creation-dialog-actions"><button type="button" onClick={onCancel}>{t("cancel")}</button><button type="button" onClick={onSave}>{mode === "entity" ? t("saveEntity") : t("saveRelation")}</button></div></aside>;
}
