import type { Dataset, E2RObject } from "../models";
import type { Locale } from "../i18n";
import { formatEntityIncidentWarning, translate } from "../i18n";
import { buildRelatedRelationDisplay } from "../related-relation-display";
type Detail = { entity: E2RObject; visibleRelationIds: string[]; relationIds: string[] };
type Props = { locale: Locale; dataset: Dataset; detail: Detail; name: string; description: string; onNameChange: (value: string) => void; onDescriptionChange: (value: string) => void; onSave: () => void; onDelete: () => void; onRelated: (id: string) => void; onClose: () => void };
export function EntityDetailDialog({ locale, dataset, detail, name, description, onNameChange, onDescriptionChange, onSave, onDelete, onRelated, onClose }: Props) {
  if (!dataset || !detail) return null;
  const originalName = typeof detail.entity.name === "string" ? detail.entity.name : "";
  const originalDescription = typeof detail.entity.description === "string" ? detail.entity.description : "";
  const incidents = dataset.relations.filter(({ sourceId, targetId }) => sourceId === detail.entity.id || targetId === detail.entity.id);
  return <><button className="detail-backdrop" type="button" aria-label={translate(locale, "closeEntityDetail")} onClick={onClose} /><aside className="detail" role="dialog" aria-modal="true" aria-labelledby="entity-detail-title"><div className="detail-header"><h3 id="entity-detail-title">{translate(locale, "entityDetailTitle")}</h3><button type="button" onClick={onClose}>{translate(locale, "close")}</button></div><div className="detail-fields"><label htmlFor="entity-name">{translate(locale, "name")}</label><input id="entity-name" type="text" autoComplete="off" value={name} onChange={(event) => onNameChange(event.target.value)} /><label htmlFor="entity-description">{translate(locale, "description")}</label><textarea id="entity-description" rows={4} value={description} onChange={(event) => onDescriptionChange(event.target.value)} /></div><div className="detail-actions"><button type="button" disabled={name === originalName && description === originalDescription} onClick={onSave}>{translate(locale, "entityDetailSave")}</button></div><dl><dt>{translate(locale, "entityShownRelations")}</dt><dd>{detail.visibleRelationIds.length}</dd><dt>{translate(locale, "entityDatasetRelations")}</dt><dd>{detail.relationIds.length}</dd></dl><details className="detail-technical-details"><summary>{translate(locale, "technicalDetails")}</summary><dl><dt>{translate(locale, "objectId")}</dt><dd className="detail-object-id">{detail.entity.id}</dd></dl></details><div className="detail-danger">{incidents.length > 0 ? <><p>{formatEntityIncidentWarning(locale, incidents.length)}</p><div className="related-relations"><span>{translate(locale, "relatedRelations")}</span>{incidents.map((relation) => { const display = buildRelatedRelationDisplay(dataset, relation); return <button type="button" key={display.relationId} onClick={() => onRelated(display.relationId)}><span className="related-relation-fields">{display.relationName && <span className="related-relation-field"><span className="related-relation-label">{translate(locale, "relatedRelationName")}</span><span className="related-relation-value">{display.relationName}</span></span>}<span className="related-relation-field"><span className="related-relation-label">{translate(locale, "relatedRelationSource")}</span><span className="related-relation-value">{display.source}</span></span><span className="related-relation-field"><span className="related-relation-label">{translate(locale, "relatedRelationTarget")}</span><span className="related-relation-value">{display.target}</span></span></span></button>; })}</div><div className="detail-actions"><button type="button" disabled>{translate(locale, "entityDeleteAction")}</button></div></> : <button type="button" onClick={onDelete}>{translate(locale, "entityDeleteAction")}</button>}</div></aside></>;
}
