import type { Dataset, E2RObject } from "../models";
type Detail = { entity: E2RObject; visibleRelationIds: string[]; relationIds: string[] };
export function EntityDetailDialog({ dataset, detail, name, description, onNameChange, onDescriptionChange, onSave, onDelete, onRelated, onClose }: { dataset: Dataset; detail: Detail; name: string; description: string; onNameChange: (value: string) => void; onDescriptionChange: (value: string) => void; onSave: () => void; onDelete: () => void; onRelated: (id: string) => void; onClose: () => void }) {

 if (!dataset || !detail || name === undefined || description === undefined || !onNameChange || !onDescriptionChange || !onSave || !onDelete || !onRelated) return null;
 const originalName = typeof detail.entity.name === "string" ? detail.entity.name : ""; const originalDescription = typeof detail.entity.description === "string" ? detail.entity.description : "";
 const incidents = dataset.relations.filter(({ sourceId, targetId }) => sourceId === detail.entity.id || targetId === detail.entity.id);
 return <><button className="detail-backdrop" type="button" aria-label="Close Entity Detail" onClick={onClose} /><aside className="detail" role="dialog" aria-modal="true" aria-labelledby="entity-detail-title"><div className="detail-header"><h3 id="entity-detail-title">Entity Detail</h3><button type="button" onClick={onClose}>Close</button></div><dl><dt>ID</dt><dd>{detail.entity.id}</dd><dt>Shown Relations</dt><dd>{detail.visibleRelationIds.length}</dd><dt>Dataset Relations</dt><dd>{detail.relationIds.length}</dd></dl><div className="detail-fields"><label htmlFor="entity-name">Name</label><input id="entity-name" type="text" value={name} onChange={(event) => onNameChange(event.target.value)} /><label htmlFor="entity-description">Description</label><textarea id="entity-description" rows={4} value={description} onChange={(event) => onDescriptionChange(event.target.value)} /></div><div className="detail-actions"><button type="button" disabled={name === originalName && description === originalDescription} onClick={onSave}>Save Entity</button></div><div className="detail-danger"><strong>Danger zone</strong>{incidents.length > 0 ? <><p>This Entity is connected by {incidents.length} Relation(s). Delete those Relations before deleting this Entity.</p><div className="related-relations"><span>Related Relations:</span>{incidents.map((relation) => <button type="button" key={relation.id} onClick={() => onRelated(relation.id)}>{typeof relation.name === "string" && relation.name.trim() ? relation.name : relation.id} — {String(relation.sourceId)} → {String(relation.targetId)}</button>)}</div><div className="detail-actions"><button type="button" disabled>Delete Entity</button></div></> : <button type="button" onClick={onDelete}>Delete Entity</button>}</div></aside></>;
}
