import type { Dataset, E2RObject } from "../models";
import type { Locale } from "../i18n";
import { formatEntityIncidentWarning, translate } from "../i18n";
type Detail = { entity: E2RObject; visibleRelationIds: string[]; relationIds: string[] };
type Props = { locale: Locale; dataset: Dataset; detail: Detail; name: string; description: string; onNameChange: (value: string) => void; onDescriptionChange: (value: string) => void; onSave: () => void; onDelete: () => void; onRelated: (id: string) => void; onClose: () => void };
export function EntityDetailDialog({ locale, dataset, detail, name, description, onNameChange, onDescriptionChange, onSave, onDelete, onRelated, onClose }: Props) {
  if (!dataset || !detail) return null;
  const originalName = typeof detail.entity.name === "string" ? detail.entity.name : "";
  const originalDescription = typeof detail.entity.description === "string" ? detail.entity.description : "";
  const incidents = dataset.relations.filter(({ sourceId, targetId }) => sourceId === detail.entity.id || targetId === detail.entity.id);
  return <><button className="detail-backdrop" type="button" aria-label={translate(locale, "closeEntityDetail")} onClick={onClose} /><aside className="detail" role="dialog" aria-modal="true" aria-labelledby="entity-detail-title"><div className="detail-header"><h3 id="entity-detail-title">{translate(locale, "entityDetailTitle")}</h3><button type="button" onClick={onClose}>{translate(locale, "close")}</button></div><dl><dt>{translate(locale, "id")}</dt><dd>{detail.entity.id}</dd><dt>{translate(locale, "entityShownRelations")}</dt><dd>{detail.visibleRelationIds.length}</dd><dt>{translate(locale, "entityDatasetRelations")}</dt><dd>{detail.relationIds.length}</dd></dl><div className="detail-fields"><label htmlFor="entity-name">{translate(locale, "name")}</label><input id="entity-name" type="text" value={name} onChange={(event) => onNameChange(event.target.value)} /><label htmlFor="entity-description">{translate(locale, "description")}</label><textarea id="entity-description" rows={4} value={description} onChange={(event) => onDescriptionChange(event.target.value)} /></div><div className="detail-actions"><button type="button" disabled={name === originalName && description === originalDescription} onClick={onSave}>{translate(locale, "detailSaveChanges")}</button></div><div className="detail-danger"><strong>{translate(locale, "dangerZone")}</strong>{incidents.length > 0 ? <><p>{formatEntityIncidentWarning(locale, incidents.length)}</p><div className="related-relations"><span>{translate(locale, "relatedRelations")}</span>{incidents.map((relation) => <button type="button" key={relation.id} onClick={() => onRelated(relation.id)}>{typeof relation.name === "string" && relation.name.trim() ? relation.name : relation.id} — {String(relation.sourceId)} → {String(relation.targetId)}</button>)}</div><div className="detail-actions"><button type="button" disabled>{translate(locale, "entityDeleteAction")}</button></div></> : <button type="button" onClick={onDelete}>{translate(locale, "entityDeleteAction")}</button>}</div></aside></>;
}
