import type { E2RObject } from "../models";
import type { Locale } from "../i18n";
import { translate } from "../i18n";
type EndpointEditing = { entities: E2RObject[]; sourceId: string; targetId: string; onSourceChange: (value: string) => void; onTargetChange: (value: string) => void };
type Props = { locale: Locale; relation: E2RObject; sourceId: string; targetId: string; source: E2RObject | null; target: E2RObject | null; name: string; description: string; endpointEditing?: EndpointEditing; onNameChange: (value: string) => void; onDescriptionChange: (value: string) => void; onSave: () => void; onDelete: () => void; onClose: () => void };
export function RelationDetailDialog({ locale, relation, sourceId, targetId, source, target, name, description, endpointEditing, onNameChange, onDescriptionChange, onSave, onDelete, onClose }: Props) {
  const originalName = typeof relation.name === "string" ? relation.name : "";
  const originalDescription = typeof relation.description === "string" ? relation.description : "";
  const endpointLabel = (entity: E2RObject) => typeof entity.name === "string" ? entity.name : entity.id;
  const endpointsUnchanged = !endpointEditing || (endpointEditing.sourceId === sourceId && endpointEditing.targetId === targetId);
  const unchanged = name === originalName && description === originalDescription && endpointsUnchanged;
  return <><button className="detail-backdrop" type="button" aria-label={translate(locale, "closeRelationDetail")} onClick={onClose} /><aside className="detail" role="dialog" aria-modal="true" aria-labelledby="relation-detail-title"><div className="detail-header"><h3 id="relation-detail-title">{translate(locale, "relationDetailTitle")}</h3><button type="button" onClick={onClose}>{translate(locale, "close")}</button></div>{endpointEditing ? <div className="detail-fields"><label htmlFor="relation-source">{translate(locale, "sourceEntity")}</label><select id="relation-source" value={endpointEditing.sourceId} onChange={(event) => endpointEditing.onSourceChange(event.target.value)}>{endpointEditing.entities.map((entity) => <option key={entity.id} value={entity.id}>{endpointLabel(entity)}</option>)}</select><label htmlFor="relation-target">{translate(locale, "targetEntity")}</label><select id="relation-target" value={endpointEditing.targetId} onChange={(event) => endpointEditing.onTargetChange(event.target.value)}>{endpointEditing.entities.map((entity) => <option key={entity.id} value={entity.id}>{endpointLabel(entity)}</option>)}</select></div> : <dl><dt>{translate(locale, "sourceEntity")}</dt><dd>{typeof source?.name === "string" ? source.name : sourceId}</dd><dt>{translate(locale, "targetEntity")}</dt><dd>{typeof target?.name === "string" ? target.name : targetId}</dd></dl>}<div className="detail-fields"><label htmlFor="relation-name">{translate(locale, "name")}</label><input id="relation-name" type="text" autoComplete="off" value={name} onChange={(event) => onNameChange(event.target.value)} /><label htmlFor="relation-description">{translate(locale, "description")}</label><textarea id="relation-description" rows={4} value={description} onChange={(event) => onDescriptionChange(event.target.value)} /></div><div className="detail-actions"><button type="button" disabled={unchanged} onClick={onSave}>{translate(locale, "relationDetailSave")}</button></div><details className="detail-technical-details"><summary>{translate(locale, "technicalDetails")}</summary><dl><dt>{translate(locale, "objectId")}</dt><dd className="detail-object-id">{relation.id}</dd></dl></details><div className="detail-danger relation-danger"><button type="button" onClick={onDelete}>{translate(locale, "relationDeleteAction")}</button></div></aside></>;
}
