import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";

type Dataset = { version: string; entities: Array<{ id: string; name?: string; description?: string }>; events: unknown[]; relations: Array<{ id: string; sourceId: string; targetId: string; name?: string }> };
type Point = { x: number; y: number };
const root = process.cwd();
const outputDirectory = path.join(root, "experimental", "frontier-actual-product-visual-sweep1");

function syntheticBipartite(leftSize: number, rightSize: number): Dataset { const left = Array.from({ length: leftSize }, (_, index) => `left-${index + 1}`); const right = Array.from({ length: rightSize }, (_, index) => `right-${index + 1}`); return { version: "1.0", entities: [...left, ...right].map((id) => ({ id, name: id.replace("-", " ") })), events: [], relations: left.flatMap((sourceId) => right.map((targetId) => ({ id: `${sourceId}-${targetId}`, sourceId, targetId, name: "connected" }))) }; }
function parallelSelfLoop(): Dataset { const ids = ["alpha", "beta", "gamma", "delta", "epsilon", "zeta", "eta", "theta"]; const pairs = [["r-ab-1", "alpha", "beta", "relates"], ["r-ab-2", "alpha", "beta", "supports"], ["r-ba-1", "beta", "alpha", "returns"], ["r-ba-2", "beta", "alpha", "reverses"], ["r-cd-1", "gamma", "delta", "links"], ["r-cd-2", "gamma", "delta", "tracks"], ["r-loop", "epsilon", "epsilon", "self monitors"], ["r-ef", "epsilon", "zeta", "connects"], ["r-fg", "zeta", "eta", "connects"], ["r-gh", "eta", "theta", "connects"], ["r-he", "theta", "epsilon", "connects"]] as const; return { version: "1.0", entities: ids.map((id) => ({ id, name: id[0]!.toUpperCase() + id.slice(1) })), events: [], relations: pairs.map(([id, sourceId, targetId, name]) => ({ id, sourceId, targetId, name })) }; }
function labelHeavyJa(): Dataset { const ids = Array.from({ length: 10 }, (_, index) => `label-n${index}`); return { version: "1.0", entities: ids.map((id, index) => ({ id, name: `日本語の長いノードラベル ${index} 災害対応計画`, description: "長い説明文を含む日本語の表示確認用ノード" })), events: [], relations: Array.from({ length: 20 }, (_, index) => ({ id: `label-r${index}`, sourceId: ids[index % ids.length]!, targetId: ids[(index * 3 + 1) % ids.length]!, name: `長い日本語Relationラベル ${index} の表示と所有関係を確認する` })) }; }
function generatedDataset(source: string): Dataset | null { const match = /^synthetic:k(\d+)-(\d+)$/.exec(source); if (match) return syntheticBipartite(Number(match[1]), Number(match[2])); if (source === "synthetic:parallel-self-loop-control") return parallelSelfLoop(); if (source === "synthetic:label-heavy-ja-10") return labelHeavyJa(); return null; }
function fingerprint(positions: Record<string, Point>) { return createHash("sha256").update(JSON.stringify(Object.entries(positions).sort(([left], [right]) => left.localeCompare(right)))).digest("hex").slice(0, 12); }
function cleanEnvironment() { const environment = { ...process.env }; for (const key of Object.keys(environment)) if (key.startsWith("E2R_")) delete environment[key]; return { ...environment, E2R_PRESENTATION_GEOMETRY_CACHE: "1", E2R_PRESENTATION_EXACT_CANDIDATE_REUSE: "1", E2R_RELAXATION_FINAL_CANONICALIZATION: "round-once", E2R_GLOBAL_PLACEMENT_ABLATION: "frontier-12", E2R_GLOBAL_PLACEMENT_MODE: "viewport-anisotropic", E2R_GLOBAL_SPACING_SCALE: ".88", E2R_GLOBAL_SPACING_Y: "1.12", E2R_GLOBAL_SPACING_STAGE2: "off" }; }
function runFixture(fixture: { id: string; locale: "en" | "ja"; source: string; surface: "acceptance" | "berlin" | "synthetic" }) { const generated = generatedDataset(fixture.source); let fixturePath = fixture.source; let temporaryPath: string | null = null; if (generated) { temporaryPath = path.join(outputDirectory, `.tmp-${fixture.id}.json`); fs.mkdirSync(outputDirectory, { recursive: true }); fs.writeFileSync(temporaryPath, JSON.stringify(generated)); fixturePath = temporaryPath; } else fixturePath = path.resolve(root, fixture.source); const started = performance.now(); const child = spawnSync(process.execPath, ["tools/generic-crossing-search.mjs", fixturePath], { cwd: root, encoding: "utf8", env: cleanEnvironment(), maxBuffer: 100 * 1024 * 1024, timeout: 30_000, killSignal: "SIGTERM" }); if (temporaryPath) fs.rmSync(temporaryPath, { force: true }); if (child.error?.code === "ETIMEDOUT") return { fixture: fixture.id, locale: fixture.locale, source: fixture.source, surface: fixture.surface, status: "budget-exhausted", elapsedMs: Math.round(performance.now() - started), selected: null }; if (child.status !== 0) throw new Error(`${fixture.id}: ${child.stderr || child.error || `exit ${child.status}`}`); const result = JSON.parse(child.stdout) as { graph: { nodes: number; edges: number }; candidates?: Array<{ family: string; positions: Record<string, Point> }>; selected?: { family: string; positions: Record<string, Point>; metrics?: Record<string, number> }; selectedPositionFingerprint?: string; profile?: { fullPresentationEvaluations: number; presentationMs: number }; searchBudget?: { globalPlacementAblation?: string } }; return { fixture: fixture.id, locale: fixture.locale, source: fixture.source, surface: fixture.surface, status: "materialized", elapsedMs: Math.round(performance.now() - started), graph: result.graph, candidateCount: result.candidates?.length ?? 0, selectedFamily: result.selected?.family ?? null, evaluationCount: result.profile?.fullPresentationEvaluations ?? null, presentationMs: result.profile?.presentationMs ?? null, selectedPositionFingerprint: result.selectedPositionFingerprint ?? (result.selected ? fingerprint(result.selected.positions) : null), selectedMetrics: result.selected?.metrics ?? null, positions: result.selected?.positions ?? null, searchArm: result.searchBudget?.globalPlacementAblation ?? "frontier-12" }; }

const fixtures = [
  ["lighthouse-en", "en", "../e2r-spec/examples/lighthouse-restoration-demo.en.e2r.json", "acceptance"], ["lighthouse-ja", "ja", "../e2r-spec/examples/lighthouse-restoration-demo.ja.e2r.json", "acceptance"],
  ["apollo-en", "en", "../e2r-spec/examples/apollo-11-mission.en.e2r.json", "acceptance"], ["apollo-ja", "ja", "../e2r-spec/examples/apollo-11-mission.ja.e2r.json", "acceptance"],
  ["berlin-wall-en", "en", "../e2r-narrative-line/src/sample/berlin-wall-history.en.e2r.json", "berlin"], ["berlin-wall-ja", "ja", "../e2r-narrative-line/src/sample/berlin-wall-history.ja.e2r.json", "berlin"],
  ["ashen-crown-en", "en", "../e2r-spec/examples/ashen-crown.en.e2r.json", "acceptance"], ["ashen-crown-ja", "ja", "../e2r-spec/examples/ashen-crown.ja.e2r.json", "acceptance"],
  ["titanic-en", "en", "../e2r-spec/examples/titanic-final-voyage.en.e2r.json", "acceptance"], ["titanic-ja", "ja", "../e2r-spec/examples/titanic-final-voyage.ja.e2r.json", "acceptance"],
  ["dense-k7-7", "en", "synthetic:k7-7", "synthetic"], ["dense-k6-8", "en", "synthetic:k6-8", "synthetic"], ["dense-k8-8", "en", "synthetic:k8-8", "synthetic"],
  ["label-heavy-ja-10", "ja", "synthetic:label-heavy-ja-10", "synthetic"], ["parallel-self-loop-control", "en", "synthetic:parallel-self-loop-control", "synthetic"],
] as const;
const rows = fixtures.map(([id, locale, source, surface]) => runFixture({ id, locale, source, surface }));
const artifact = { contract: "LIAISONSCAPE-FRONTIER-ACTUAL-PRODUCT-VISUAL-SWEEP-1", diagnosticOnly: true, candidateIdentity: "current-source Frontier-12 reconstruction; no historical artifact replay", searchEnvironment: "frontier-12 + viewport-anisotropic + round-once; same environment for every row", visualInspectionRequired: true, productAuthoritiesChanged: false, rows, readiness: { humanReview: "NOT READY", qualitySolver: "HOLD / NOT ESTABLISHED", productionProvider: "NOT ESTABLISHED", productIntegration: "HOLD", initialLayoutReleaseBlocker: "OPEN" }, classification: "MATERIALIZED / VISUAL SWEEP PENDING" };
fs.mkdirSync(outputDirectory, { recursive: true }); fs.writeFileSync(path.join(outputDirectory, "result-summary.json"), `${JSON.stringify(artifact, null, 2)}\n`); console.log(JSON.stringify(rows.map(({ fixture, locale, source, status, graph, candidateCount, selectedFamily, evaluationCount, elapsedMs, selectedPositionFingerprint }) => ({ fixture, locale, source, status, graph, candidateCount, selectedFamily, evaluationCount, elapsedMs, selectedPositionFingerprint })), null, 2));
