import fs from "node:fs";
import path from "node:path";
import { createHash } from "node:crypto";
import { buildEntityGraph } from "../src/dataset.ts";
import { deriveAutomaticLayoutQualityMetrics } from "../src/automatic-layout-quality.ts";
import { deriveAutomaticLayoutVisualRiskMetrics } from "../src/automatic-layout-visual-risk.ts";
import { deriveBoundedAutomaticPresentation, type RoutingGraphEdge } from "../src/graph-presentation.ts";
import { ENTITY_ATTACHMENT_SHAPE, fitGraphView, placeNodeLabel, type LabelRect } from "../src/viewport.ts";

type Point = { x: number; y: number };
type Rect = { x: number; y: number; width: number; height: number };
type Dataset = { version: string; entities: Array<{ id: string; name?: string; description?: string }>; events: unknown[]; relations: Array<{ id: string; sourceId: string; targetId: string; name?: string }> };
type Case = { id: string; source: string; dataset: Dataset; nodes: Array<{ id: string; label: string; description: string; x: number; y: number }>; edges: RoutingGraphEdge[] };
type Candidate = ReturnType<typeof metrics>;

const root = process.cwd();
const sourcePath = path.join(root, "experimental", "common-fixture-cross-lineage-comparison1", "result-summary.json");
const outputDirectory = path.join(root, "experimental", "structural-seeded-capacity-refinement1");
const sourceArtifact = JSON.parse(fs.readFileSync(sourcePath, "utf8")) as { rows: Array<{ fixture: string; source: string; topologyDigest: string; candidates: { fast: Candidate; auto: Candidate; structural: Array<Candidate & { replay?: string; elapsedMs?: number; fullPresentationEvaluations?: number }> } }> };

function syntheticDense(): Dataset { const left = Array.from({ length: 7 }, (_, index) => `left-${index + 1}`); const right = Array.from({ length: 7 }, (_, index) => `right-${index + 1}`); return { version: "1.0", entities: [...left, ...right].map((id) => ({ id, name: id.replace("-", " ") })), events: [], relations: left.flatMap((sourceId) => right.map((targetId) => ({ id: `${sourceId}-${targetId}`, sourceId, targetId, name: "connected" }))) }; }
function syntheticParallelLoop(): Dataset { const ids = ["alpha", "beta", "gamma", "delta", "epsilon", "zeta", "eta", "theta"]; const pairs = [["r-ab-1", "alpha", "beta", "relates"], ["r-ab-2", "alpha", "beta", "supports"], ["r-ba-1", "beta", "alpha", "returns"], ["r-ba-2", "beta", "alpha", "reverses"], ["r-cd-1", "gamma", "delta", "links"], ["r-cd-2", "gamma", "delta", "tracks"], ["r-loop", "epsilon", "epsilon", "self monitors"], ["r-ef", "epsilon", "zeta", "connects"], ["r-fg", "zeta", "eta", "connects"], ["r-gh", "eta", "theta", "connects"], ["r-he", "theta", "epsilon", "connects"]] as const; return { version: "1.0", entities: ids.map((id) => ({ id, name: id[0]!.toUpperCase() + id.slice(1) })), events: [], relations: pairs.map(([id, sourceId, targetId, name]) => ({ id, sourceId, targetId, name })) }; }
function loadDataset(source: string): Dataset { if (source === "synthetic:k7-7") return syntheticDense(); if (source === "synthetic:parallel-self-loop-control") return syntheticParallelLoop(); return JSON.parse(fs.readFileSync(path.resolve(root, source), "utf8")) as Dataset; }
function makeCase(id: string, source: string): Case { const dataset = loadDataset(source); const graph = buildEntityGraph(dataset); const names = new Map(dataset.relations.map((relation) => [relation.id, relation.name ?? relation.id])); return { id, source, dataset, nodes: graph.nodes, edges: graph.edges.map((edge) => ({ ...edge, label: names.get(edge.id) ?? edge.id })) }; }
function components(testCase: Case): string[][] { const neighbours = new Map(testCase.nodes.map(({ id }) => [id, new Set<string>()])); for (const edge of testCase.edges) if (edge.sourceId !== edge.targetId) { neighbours.get(edge.sourceId)?.add(edge.targetId); neighbours.get(edge.targetId)?.add(edge.sourceId); } const remaining = new Set(neighbours.keys()); const result: string[][] = []; while (remaining.size) { const seed = [...remaining].sort()[0]!; const queue = [seed]; const ids: string[] = []; remaining.delete(seed); while (queue.length) { const id = queue.shift()!; ids.push(id); for (const next of [...(neighbours.get(id) ?? [])].sort()) if (remaining.delete(next)) queue.push(next); } result.push(ids.sort()); } return result.sort((left, right) => left[0]!.localeCompare(right[0]!)); }
function presentation(testCase: Case, positions: Record<string, Point>) { const provisionalNodeLabels = testCase.nodes.map((node) => placeNodeLabel(positions[node.id]!, node.label, node.description, [], testCase.nodes.filter(({ id }) => id !== node.id).map(({ id }) => positions[id]!), [])); return deriveBoundedAutomaticPresentation({ graph: { nodes: testCase.nodes, edges: testCase.edges }, positions, edgeCurveOffsets: {}, selfLoopOverrides: {}, provisionalNodeLabels, previousNodeLabelPlacements: new Map<string, LabelRect>(), previousRelationLabelPlacements: new Map<string, LabelRect>(), manualNodeLabelOffsets: new Map(), manualRelationLabelAnchors: new Map(), feedbackEnabled: true }); }
function rect(point: Point, width: number, height: number): Rect { return { x: point.x, y: point.y, width, height }; }
function overlaps(left: Rect, right: Rect): boolean { return Math.abs(left.x - right.x) < (left.width + right.width) / 2 && Math.abs(left.y - right.y) < (left.height + right.height) / 2; }
function distance(left: Point, right: Point): number { return Math.hypot(left.x - right.x, left.y - right.y); }
function occupied(testCase: Case, positions: Record<string, Point>, current = presentation(testCase, positions)) { const bodies = testCase.nodes.map((node) => [node.id, rect(positions[node.id]!, ENTITY_ATTACHMENT_SHAPE.halfWidth * 2, ENTITY_ATTACHMENT_SHAPE.halfHeight * 2)] as const); const nodeLabels = [...current.nodeLabels.entries()]; const relationLabels = [...current.relationLabels.entries()]; let nodeBodyNodeBody = 0; let nodeLabelNodeBody = 0; let relationLabelNodeBody = 0; let nodeLabelNodeLabel = 0; let nodeLabelRelationLabel = 0; let relationLabelRelationLabel = 0; for (let left = 0; left < bodies.length; left += 1) for (let right = left + 1; right < bodies.length; right += 1) if (overlaps(bodies[left]![1], bodies[right]![1])) nodeBodyNodeBody += 1; for (const [nodeId, label] of nodeLabels) for (const [bodyId, body] of bodies) if (nodeId !== bodyId && overlaps(label, body)) nodeLabelNodeBody += 1; for (const [, label] of relationLabels) for (const [, body] of bodies) if (overlaps(label, body)) relationLabelNodeBody += 1; for (let left = 0; left < nodeLabels.length; left += 1) for (let right = left + 1; right < nodeLabels.length; right += 1) if (overlaps(nodeLabels[left]![1], nodeLabels[right]![1])) nodeLabelNodeLabel += 1; for (const [, nodeLabel] of nodeLabels) for (const [, relationLabel] of relationLabels) if (overlaps(nodeLabel, relationLabel)) nodeLabelRelationLabel += 1; for (let left = 0; left < relationLabels.length; left += 1) for (let right = left + 1; right < relationLabels.length; right += 1) if (overlaps(relationLabels[left]![1], relationLabels[right]![1])) relationLabelRelationLabel += 1; const totalOccupiedOverlaps = nodeBodyNodeBody + nodeLabelNodeBody + relationLabelNodeBody + nodeLabelNodeLabel + nodeLabelRelationLabel + relationLabelRelationLabel; return { nodeBodyNodeBody, nodeLabelNodeBody, relationLabelNodeBody, nodeLabelNodeLabel, nodeLabelRelationLabel, relationLabelRelationLabel, totalOccupiedOverlaps, hardFeasible: totalOccupiedOverlaps === 0 }; }
function orderingChanges(testCase: Case, seed: Record<string, Point>, candidate: Record<string, Point>) { let changes = 0; for (const ids of components(testCase)) for (let left = 0; left < ids.length; left += 1) for (let right = left + 1; right < ids.length; right += 1) { const a = seed[ids[left]!]!; const b = seed[ids[right]!]!; const c = candidate[ids[left]!]!; const d = candidate[ids[right]!]!; const seedX = Math.sign(a.x - b.x); const seedY = Math.sign(a.y - b.y); if (seedX !== Math.sign(c.x - d.x) || seedY !== Math.sign(c.y - d.y)) changes += 1; } return changes; }
function metrics(testCase: Case, family: string, positions: Record<string, Point>, source: string, seed?: Record<string, Point>) { const current = presentation(testCase, positions); const quality = deriveAutomaticLayoutQualityMetrics({ nodes: testCase.nodes, edges: testCase.edges, positions, presentation: current }); const visualRisk = deriveAutomaticLayoutVisualRiskMetrics({ positions, presentation: current }); const fit = fitGraphView(Object.values(positions), 800, 500); return { family, source, positions, score: quality.score, structural: { nodeOverlap: quality.overlapPairs, crossings: quality.crossings, minimumSeparation: quality.minimumSeparation, extent: quality.extent, componentCount: components(testCase).length }, presentation: { labelRouteHits: quality.labelRouteHits, labelNear20: quality.labelNear20, labelOverlap: quality.labelOverlap, routeMedian: quality.routeMedian, routeMax: quality.routeMax, fitScale: fit.scale, visualLabelOverlap: visualRisk.totalLabelOverlapPairs, foreignRouteHits: visualRisk.foreignRouteRelationLabelHits, ownershipAmbiguity: visualRisk.ownershipAmbiguityCount }, occupied: occupied(testCase, positions, current), invariants: { orderingChanges: seed ? orderingChanges(testCase, seed, positions) : 0 } }; }
function labelCapacity(testCase: Case, source: Record<string, Point>, intensity: number) { const current = presentation(testCase, source); const transformed = new Map<string, Point>(); for (const ids of components(testCase)) { const points = ids.map((id) => source[id]!); const center = { x: points.reduce((sum, point) => sum + point.x, 0) / points.length, y: points.reduce((sum, point) => sum + point.y, 0) / points.length }; const nodeLabels = ids.map((id) => current.nodeLabels.get(id)!).filter(Boolean); const relations = testCase.edges.filter((edge) => ids.includes(edge.sourceId) && ids.includes(edge.targetId)); const relationLabels = relations.map((edge) => current.relationLabels.get(edge.id)!).filter(Boolean); const nodeWidth = Math.max(...nodeLabels.map(({ width }) => width), 48); const nodeHeight = Math.max(...nodeLabels.map(({ height }) => height), 24); const relationWidth = relationLabels.reduce((sum, label) => sum + label.width, 0) / Math.max(1, relationLabels.length); const degreeDemand = relations.length / Math.max(1, ids.length); const scaleX = 1 + intensity * Math.min(1.15, nodeWidth / 180 + relationWidth / 360 + degreeDemand / 12); const scaleY = 1 + intensity * Math.min(0.75, nodeHeight / 90 + degreeDemand / 18); for (const id of ids) { const point = source[id]!; transformed.set(id, { x: center.x + (point.x - center.x) * scaleX, y: center.y + (point.y - center.y) * scaleY }); } } const packed: Record<string, Point> = {}; let cursor = 0; for (const ids of components(testCase)) { const points = ids.map((id) => transformed.get(id)!); const minX = Math.min(...points.map(({ x }) => x)); const maxX = Math.max(...points.map(({ x }) => x)); const centerY = points.reduce((sum, point) => sum + point.y, 0) / points.length; for (const id of ids) { const point = transformed.get(id)!; packed[id] = { x: cursor + 48 + point.x - minX, y: 250 + point.y - centerY }; } cursor += 48 + maxX - minX; } return packed; }
function infiniteCanvas(testCase: Case, source: Record<string, Point>) { const current = presentation(testCase, source); const groups = components(testCase).flatMap((component) => { const count = component.length >= 12 ? 3 : component.length >= 8 ? 2 : 1; if (count === 1) return [component]; const seeds = [component.slice().sort()[0]!]; while (seeds.length < count) seeds.push(component.filter((id) => !seeds.includes(id)).sort((left, right) => Math.min(...seeds.map((seed) => distance(source[right]!, source[seed]!))) - Math.min(...seeds.map((seed) => distance(source[left]!, source[seed]!))) || left.localeCompare(right))[0]!); const output = seeds.map(() => [] as string[]); for (const id of component.slice().sort()) { const target = seeds.reduce((best, seed, index) => distance(source[id]!, source[seed]!) < distance(source[id]!, source[seeds[best]!]!) ? index : best, 0); output[target]!.push(id); } return output.filter((group) => group.length); }); const packed: Record<string, Point> = {}; for (let index = 0; index < groups.length; index += 1) { const ids = groups[index]!; const points = ids.map((id) => source[id]!); const center = { x: points.reduce((sum, point) => sum + point.x, 0) / points.length, y: points.reduce((sum, point) => sum + point.y, 0) / points.length }; const labels = ids.map((id) => current.nodeLabels.get(id)!).filter(Boolean); const relations = testCase.edges.filter((edge) => ids.includes(edge.sourceId) && ids.includes(edge.targetId)); const demand = relations.length / Math.max(1, ids.length); const scaleX = 1 + 0.94 * Math.min(1.15, Math.max(48, ...labels.map(({ width }) => width)) / 150 + demand / 10); const scaleY = 1 + 0.94 * Math.min(0.9, Math.max(24, ...labels.map(({ height }) => height)) / 90 + demand / 18); const transformed = ids.map((id) => { const point = source[id]!; return [id, { x: center.x + (point.x - center.x) * scaleX, y: center.y + (point.y - center.y) * scaleY }] as const; }); const minX = Math.min(...transformed.map(([, point]) => point.x)); const minY = Math.min(...transformed.map(([, point]) => point.y)); const width = Math.max(...transformed.map(([, point]) => point.x)) - minX; const height = Math.max(...transformed.map(([, point]) => point.y)) - minY; for (const [id, point] of transformed) packed[id] = { x: (index % 2) * (width + 110) + point.x - minX, y: Math.floor(index / 2) * (height + 92) + point.y - minY }; } return packed; }
function occupiedFeedback(testCase: Case, source: Record<string, Point>, sweeps: number) { const positions = Object.fromEntries(Object.entries(source).map(([id, point]) => [id, { ...point }])); for (let sweep = 0; sweep < sweeps; sweep += 1) { const current = presentation(testCase, positions); const bodies = new Map(testCase.nodes.map((node) => [node.id, rect(positions[node.id]!, 64, 64)])); const labels = [...current.nodeLabels.entries()]; const relationLabels = [...current.relationLabels.entries()]; const owners = new Map(testCase.edges.map((edge) => [edge.id, [edge.sourceId, edge.targetId]])); const forces = new Map<string, Point>(); const add = (ids: string[], vector: Point) => { for (const id of [...new Set(ids)].sort()) forces.set(id, { x: (forces.get(id)?.x ?? 0) + vector.x / Math.max(1, ids.length), y: (forces.get(id)?.y ?? 0) + vector.y / Math.max(1, ids.length) }); }; const push = (left: Rect, right: Rect, leftOwners: string[], rightOwners: string[]) => { if (!overlaps(left, right)) return; const dx = right.x - left.x; const dy = right.y - left.y; const length = Math.hypot(dx, dy) || 1; const depth = Math.max(1, Math.min((left.width + right.width) / 2 - Math.abs(dx), (left.height + right.height) / 2 - Math.abs(dy)) + 1); const vector = { x: dx / length * depth, y: dy / length * depth }; add(leftOwners, { x: -vector.x, y: -vector.y }); add(rightOwners, vector); }; const bodyEntries = [...bodies.entries()]; for (let left = 0; left < bodyEntries.length; left += 1) for (let right = left + 1; right < bodyEntries.length; right += 1) push(bodyEntries[left]![1], bodyEntries[right]![1], [bodyEntries[left]![0]], [bodyEntries[right]![0]]); for (const [nodeId, label] of labels) for (const [bodyId, body] of bodyEntries) if (nodeId !== bodyId) push(label, body, [nodeId], [bodyId]); for (const [relationId, label] of relationLabels) for (const [bodyId, body] of bodyEntries) push(label, body, owners.get(relationId) ?? [], [bodyId]); for (let left = 0; left < labels.length; left += 1) for (let right = left + 1; right < labels.length; right += 1) push(labels[left]![1], labels[right]![1], [labels[left]![0]], [labels[right]![0]]); if (!forces.size) break; for (const [id, force] of forces) positions[id] = { x: positions[id]!.x + force.x * 0.8, y: positions[id]!.y + force.y * 0.8 }; } return positions; }
function invariant(seed: Candidate, candidate: Candidate) { return candidate.structural.crossings <= seed.structural.crossings && candidate.structural.nodeOverlap <= seed.structural.nodeOverlap && candidate.invariants.orderingChanges === 0; }
function choose(seed: Candidate, candidates: Candidate[]) { const feasible = candidates.filter((candidate) => invariant(seed, candidate)); return { selected: feasible.slice().sort((left, right) => left.occupied.totalOccupiedOverlaps - right.occupied.totalOccupiedOverlaps || left.presentation.visualLabelOverlap - right.presentation.visualLabelOverlap || left.presentation.foreignRouteHits - right.presentation.foreignRouteHits || left.score - right.score)[0] ?? null, candidateCount: candidates.length, structurallyPreservingCount: feasible.length, rejectedFamilies: candidates.filter((candidate) => !invariant(seed, candidate)).map(({ family }) => family) }; }
function digest(row: { topologyDigest: string }) { return row.topologyDigest; }
function timed<T>(run: () => T) { const started = performance.now(); const value = run(); return { value, elapsedMs: performance.now() - started }; }

const fixtureCases = new Map(sourceArtifact.rows.map((row) => [row.fixture, makeCase(row.fixture, row.source)]));
const rows = sourceArtifact.rows.map((row) => {
  const testCase = fixtureCases.get(row.fixture)!;
  const frontier = row.candidates.structural.find((candidate) => candidate.family.startsWith("structural-frontier"))!;
  const post = row.candidates.structural.find((candidate) => candidate.family.startsWith("post-structural")) ?? row.candidates.structural[0]!;
  const seeds = [frontier, post].map((seed) => {
    const seedMetric = metrics(testCase, seed.family, seed.positions, "current-source-reconstruction");
    const labelRun = timed(() => [0.55, 0.8, 1].map((intensity) => metrics(testCase, `${seed.family}+label-capacity-${intensity}`, labelCapacity(testCase, seed.positions, intensity), "current-source-reconstruction", seed.positions)));
    const labelCandidates = labelRun.value;
    const label = choose(seedMetric, labelCandidates);
    const labelPositions = label.selected?.positions ?? seed.positions;
    const infiniteRun = timed(() => metrics(testCase, `${seed.family}+infinite-canvas`, infiniteCanvas(testCase, labelPositions), "current-source-reconstruction", seed.positions));
    const infiniteCandidate = infiniteRun.value;
    const infinite = choose(seedMetric, [infiniteCandidate]);
    const infinitePositions = infinite.selected?.positions ?? infiniteCandidate.positions;
    const occupiedRun = timed(() => [2, 4, 8].map((sweeps) => metrics(testCase, `${seed.family}+infinite+occupied-${sweeps}`, occupiedFeedback(testCase, infinitePositions, sweeps), "current-source-reconstruction", seed.positions)));
    const occupiedCandidates = occupiedRun.value;
    const occupiedSelected = choose(seedMetric, occupiedCandidates);
    return { seed: seedMetric, labelCapacity: { ...label, elapsedMs: labelRun.elapsedMs, candidates: labelCandidates }, infiniteCanvas: { ...infinite, elapsedMs: infiniteRun.elapsedMs, candidates: [infiniteCandidate] }, occupiedGeometry: { ...occupiedSelected, elapsedMs: occupiedRun.elapsedMs, candidates: occupiedCandidates }, source: { family: seed.family, replay: seed.replay, elapsedMs: seed.elapsedMs, fullPresentationEvaluations: seed.fullPresentationEvaluations } };
  });
  return { fixture: row.fixture, topologyDigest: digest(row), graph: { nodes: testCase.nodes.length, relations: testCase.edges.length }, controls: { fast: row.candidates.fast, auto: row.candidates.auto }, seeds };
});
const artifact = { contract: "LIAISONSCAPE-STRUCTURAL-SEEDED-CAPACITY-REFINEMENT-1", diagnosticOnly: true, primarySeed: "Frontier", qualityReference: "Post", seedRationale: "Frontier retained canonical zero-crossing signal with materially fewer current-source Product evaluations than Post on the common fixture artifact; Post remains the quality reference/control.", structuralInvariants: ["component-local pair ordering", "crossings must not increase", "Node-body overlap must not increase"], commonFixtureSource: "experimental/common-fixture-cross-lineage-comparison1/result-summary.json", productAuthoritiesChanged: false, productionMetricMutation: false, rows, classification: "STRUCTURAL-SEEDED REFINEMENT / PENDING-INTERPRETATION", readiness: { humanReview: "NOT READY", qualitySolver: "HOLD / NOT ESTABLISHED", productionProvider: "NOT ESTABLISHED", productIntegration: "HOLD", initialLayoutReleaseBlocker: "OPEN" } };
fs.mkdirSync(outputDirectory, { recursive: true }); fs.writeFileSync(path.join(outputDirectory, "result-summary.json"), `${JSON.stringify(artifact, null, 2)}\n`); console.log(JSON.stringify(rows.map((row) => ({ fixture: row.fixture, topologyDigest: row.topologyDigest, seeds: row.seeds.map((seed) => ({ family: seed.source.family, seed: { crossings: seed.seed.structural.crossings, occupied: seed.seed.occupied.totalOccupiedOverlaps, extent: seed.seed.structural.extent }, label: { preserving: seed.labelCapacity.structurallyPreservingCount, selected: seed.labelCapacity.selected?.family ?? null }, infinite: { preserving: seed.infiniteCanvas.structurallyPreservingCount, selected: seed.infiniteCanvas.selected?.family ?? null }, occupied: { preserving: seed.occupiedGeometry.structurallyPreservingCount, selected: seed.occupiedGeometry.selected?.family ?? null } })) })), null, 2));
